### ISSUE TITLE
[微信端]c-loading组件在快速显示隐藏的时候会先出现在页面顶部然后回到页面中间

### ISSUE THREAD

**Issue by z-mirror** [chameleon-team/cml-ui#5]
![c-loading-bug](https://user-images.githubusercontent.com/27213974/56214116-d7e1cc80-608f-11e9-81f7-a0701c8edf06.gif)

**Comment by z-mirror** [comment]
支付宝端也存在相同的问题

**Comment by startheart** [comment]
请确认父容器有占位高度，可以贴下代码吗

**Comment by z-mirror** [comment]
> 请确认父容器有占位高度，可以贴下代码吗

![image](https://user-images.githubusercontent.com/27213974/59318059-4346c400-8cf8-11e9-8a3a-15aa5a86fd0b.png)
![image](https://user-images.githubusercontent.com/27213974/59318073-56599400-8cf8-11e9-9fb4-7ab04d4a0dbc.png)
父元素高度设置了也是一样的，这个不是高度的问题，之前有做过测试，像是flex布局下元素先从start变到了center；

**Comment by huyuangang** [comment]
使用cml-ui@0.2.0-alpha.4
